Repository jupyterhub/systemdspawner, pull requests merged in 2023-06, with the labels that each got.

#127 Replace deprecated MemoryLimit with MemoryMax, remove fixme notes
  systemdspawner/systemdspawner.py
Labels: maintenance

#121 Add changelog for 1.0.0
  CHANGELOG.md
  README.md
Labels: documentation

#129 ensure executable paths are absolute
  systemdspawner/systemd.py
  tests/test_systemd.py
Labels: bug

#132 Cache check of systemd version
  systemdspawner/systemd.py
Labels: maintenance

#133 Use warnings.warn instead of self.log.warning to help avoid duplications
  systemdspawner/systemd.py
  systemdspawner/systemdspawner.py
Labels: maintenance

#131 Add changelog for 1.0.1
  CHANGELOG.md
Labels: documentation
