Repository jupyterhub/systemdspawner, pull requests merged in 2023-05, with the labels that each got.

#108 Add pre-commit for automated formatting
  .flake8
  .pre-commit-config.yaml
  README.md
  jupyterhub.service
  pyproject.toml
  setup.py
  systemdspawner/systemd.py
  systemdspawner/systemdspawner.py
  tests/test_systemd.py
Labels: maintenance

#114 maint, breaking: require python 3.8+, jupyterhub 2.3.0+, tornado 5.1+
  pyproject.toml
  setup.py
Labels: maintenance, breaking

#113 ci: add dependabot to bump future github actions
  .github/dependabot.yaml
Labels: ci

#91 Disable user sudo by default
  systemdspawner/systemdspawner.py
Labels: maintenance, breaking

#111 readme: remove resources section and link to discourse forum instead of mailing list
  README.md
Labels: documentation

#118 docs: add some explanatory notes in files, and small details
  README.md
  check-kernel.bash
  examples/README.md
  examples/jupyterhub.service
Labels: documentation

#119 refactor: remove no longer needed pytest.mark.asyncio
  tests/test_systemd.py
Labels: maintenance

#117 Require systemd v243+, recommend systemd v245+, test against systemd v245
  .github/workflows/test.yaml
  README.md
  systemdspawner/systemd.py
  systemdspawner/systemdspawner.py
  tests/test_systemd.py
Labels: maintenance, breaking

#120 Add basic start/stop test against a jupyterhub
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  pyproject.toml
  setup.py
  tests/conftest.py
  tests/test_systemdspawner.py
Labels: maintenance

#124 Rely on systemd-run's --working-directory, and refactor for readability
  systemdspawner/systemd.py
Labels: maintenance
